export const ADD_TO_CART = 'ADD_TO_CART'
export const GET_ARTICLE = 'GET_ARTICLE'
export const GET_ARTICLEBYID = 'GET_ARTICLEBYID'
export const GET_TAGS = 'GET_TAGS'
export const ADD_COMMENT = 'ADD_COMMENT'
export const GET_COUNT = 'GET_COUNT'
